export const ICON_CATEGORIES = [
  {
    title: 'Ăn uống & Mua sắm',
    tabIcon: 'cart-shopping',
    icons: [
      { name: 'Ăn uống', nameEn: 'Eating', icon: 'utensils' },
      { name: 'Nước', nameEn: 'Water', icon: 'mug-hot' },
      { name: 'Pizza', nameEn: 'Pizza', icon: 'pizza-slice' },
      { name: 'Burger', nameEn: 'Burger', icon: 'burger' },
      { name: 'Kem', nameEn: 'Ice cream', icon: 'ice-cream' },
      { name: 'Rượu', nameEn: 'Wine', icon: 'wine-glass' },
      { name: 'Bia', nameEn: 'Beer', icon: 'beer-mug-empty' },
      { name: 'Thẻ bài', nameEn: 'Tag', icon: 'tag' },
      { name: 'Tôm', nameEn: 'Shrimp', icon: 'shrimp' },
      { name: 'Cà rốt', nameEn: 'Carrot', icon: 'carrot' },
      { name: 'Táo', nameEn: 'Apple', icon: 'apple-whole' },
      { name: 'Bát ăn', nameEn: 'Bowl food', icon: 'bowl-food' },
      { name: 'Bánh quy', nameEn: 'Cookie', icon: 'cookie' },
      { name: 'Cá', nameEn: 'Fish', icon: 'fish' },
      { name: 'Hotdog', nameEn: 'Hotdog', icon: 'hotdog' },
      { name: 'Trứng', nameEn: 'Egg', icon: 'egg' },
      { name: 'Cây kẹo', nameEn: 'Candy cane', icon: 'candy-cane' },
      { name: 'Bánh ngọt', nameEn: 'Cake', icon: 'cake-candles' },
    ],
  },
  {
    title: 'Di chuyển & Du lịch',
    tabIcon: 'car-side',
    icons: [
      { name: 'Xe hơi', nameEn: 'Car', icon: 'car-side' },
      { name: 'Xe máy', nameEn: 'Motorcycle', icon: 'motorcycle' },
      { name: 'Xe buýt', nameEn: 'Bus', icon: 'bus' },
      { name: 'Tàu hỏa', nameEn: 'Train', icon: 'train' },
      { name: 'Máy bay', nameEn: 'Plane', icon: 'plane' },
      { name: 'Trạm xăng', nameEn: 'Gas Station', icon: 'gas-pump' },
      { name: 'Dầu nhớt', nameEn: 'Oil Can', icon: 'oil-can' },
      { name: 'Sửa chữa', nameEn: 'Repair', icon: 'wrench' },
      { name: 'Taxi', nameEn: 'Taxi', icon: 'taxi' },
      { name: 'Xe đạp', nameEn: 'Bicycle', icon: 'bicycle' },
      { name: 'Bản đồ', nameEn: 'Map Location', icon: 'map-location-dot' },
      { name: 'Va li', nameEn: 'Suitcase', icon: 'suitcase' },
      { name: 'Xe nhà lưu động', nameEn: 'Caravan', icon: 'caravan' },
      { name: 'Tàu thủy', nameEn: 'Ship', icon: 'ship' },
      { name: 'Xe tải', nameEn: 'Truck', icon: 'truck' },
      { name: 'Mũ bảo hiểm', nameEn: 'Safety Helmet', icon: 'helmet-safety' },
      {
        name: 'Đèn giao thông',
        nameEn: 'Traffic Light',
        icon: 'traffic-light',
      },
      { name: 'Mỏ neo', nameEn: 'Anchor', icon: 'anchor' },
      { name: 'Hộ chiếu', nameEn: 'Passport', icon: 'passport' },
      { name: 'Khách sạn', nameEn: 'Hotel', icon: 'hotel' },
      { name: 'Núi non', nameEn: 'Mountain', icon: 'mountain-sun' },
      { name: 'Bãi biển', nameEn: 'Beach', icon: 'umbrella-beach' },
    ],
  },
  {
    title: 'Nhà cửa & Tiện ích',
    tabIcon: 'house',
    icons: [
      { name: 'Nhà ở', nameEn: 'House', icon: 'house' },
      { name: 'Chủ nhà', nameEn: 'House User', icon: 'house-user' },
      { name: 'Tiền điện', nameEn: 'Electricity', icon: 'bolt' },
      { name: 'Vòi nước', nameEn: 'Faucet', icon: 'faucet' },
      { name: 'Tiền nước', nameEn: 'Water', icon: 'droplet' },
      { name: 'Ghế sofa', nameEn: 'Couch', icon: 'couch' },
      { name: 'Tivi', nameEn: 'Television', icon: 'tv' },
      { name: 'Giường ngủ', nameEn: 'Bed', icon: 'bed' },
      { name: 'Vòi sen', nameEn: 'Shower', icon: 'shower' },
      { name: 'Nhà bếp', nameEn: 'Kitchen Set', icon: 'kitchen-set' },
      { name: 'Chổi quét', nameEn: 'Broom', icon: 'broom' },
      { name: 'Ổ cắm điện', nameEn: 'Plug', icon: 'plug' },
      { name: 'Wifi', nameEn: 'Wifi', icon: 'wifi' },
      { name: 'Thùng rác', nameEn: 'Trash Can', icon: 'trash-can' },
      { name: 'Chìa khóa', nameEn: 'Key', icon: 'key' },
      { name: 'Quạt', nameEn: 'Fan', icon: 'fan' },
      { name: 'Búa', nameEn: 'Hammer', icon: 'hammer' },
      { name: 'Cọ lăn sơn', nameEn: 'Paint Roller', icon: 'paint-roller' },
      { name: 'Dụng cụ sửa chữa', nameEn: 'Tools', icon: 'screwdriver-wrench' },
      { name: 'Máy lạnh', nameEn: 'Air Conditioner', icon: 'snowflake' },
      { name: 'Bếp gas', nameEn: 'Fire Burner', icon: 'fire-burner' },
      { name: 'Giấy vệ sinh', nameEn: 'Toilet Paper', icon: 'toilet-paper' },
      { name: 'Ghế', nameEn: 'Chair', icon: 'chair' },
    ],
  },
  {
    title: 'Sức khỏe & Giáo dục',
    tabIcon: 'graduation-cap',
    icons: [
      { name: 'Nhịp tim', nameEn: 'Heart rate', icon: 'heart-pulse' },
      { name: 'Ống nghe', nameEn: 'Stethoscope', icon: 'stethoscope' },
      { name: 'Thuốc', nameEn: 'Pills', icon: 'pills' },
      { name: 'Bệnh viện', nameEn: 'Hospital', icon: 'hospital' },
      { name: 'Nha khoa', nameEn: 'Tooth', icon: 'tooth' },
      { name: 'Giáo dục', nameEn: 'Education', icon: 'graduation-cap' },
      { name: 'Sách', nameEn: 'Book', icon: 'book' },
      { name: 'Trường học', nameEn: 'School', icon: 'school' },
      { name: 'Trí tuệ', nameEn: 'Brain', icon: 'brain' },
      { name: 'Kính hiển vi', nameEn: 'Microscope', icon: 'microscope' },
      { name: 'Thể hình', nameEn: 'Gym', icon: 'dumbbell' },
      { name: 'Bác sĩ', nameEn: 'Doctor', icon: 'user-doctor' },
      { name: 'Băng cá nhân', nameEn: 'Bandage', icon: 'bandage' },
      { name: 'Tiêm chủng', nameEn: 'Syringe', icon: 'syringe' },
      { name: 'Túi y tế', nameEn: 'Medical kit', icon: 'kit-medical' },
      { name: 'Mắt kính', nameEn: 'Glasses', icon: 'glasses' },
      { name: 'ADN', nameEn: 'DNA', icon: 'dna' },
      { name: 'Tủ sách', nameEn: 'Books', icon: 'swatchbook' },
      { name: 'Bút máy', nameEn: 'Pen nib', icon: 'pen-nib' },
      { name: 'Bút chì', nameEn: 'Pencil', icon: 'pencil' },
      { name: 'Bảng màu', nameEn: 'Palette', icon: 'palette' },
      { name: 'Bảng đen', nameEn: 'Chalkboard', icon: 'chalkboard' },
    ],
  },
  {
    title: 'Tài chính & Công việc',
    tabIcon: 'money-bill-1',
    icons: [
      { name: 'Tiền mặt', nameEn: 'Cash', icon: 'money-bill-1' },
      { name: 'Séc', nameEn: 'Check', icon: 'money-check-dollar' },
      { name: 'Công việc', nameEn: 'Briefcase', icon: 'briefcase' },
      { name: 'Thẻ tín dụng', nameEn: 'Credit card', icon: 'credit-card' },
      { name: 'Tiền xu', nameEn: 'Coins', icon: 'coins' },
      { name: 'Hóa đơn', nameEn: 'Receipt', icon: 'receipt' },
      { name: 'Biểu đồ', nameEn: 'Chart', icon: 'chart-line' },
      { name: 'Heo đất', nameEn: 'Piggy bank', icon: 'piggy-bank' },
      { name: 'Ví tiền', nameEn: 'Wallet', icon: 'wallet' },
      { name: 'Thu nhập', nameEn: 'Income', icon: 'hand-holding-dollar' },
      { name: 'Túi tiền', nameEn: 'Money sack', icon: 'sack-dollar' },
      { name: 'Hóa đơn thuế', nameEn: 'Invoice', icon: 'file-invoice-dollar' },
      { name: 'Ngân hàng', nameEn: 'bank', icon: 'building-columns' },
      { name: 'Đá quý', nameEn: 'Gem', icon: 'gem' },
      { name: 'Két sắt', nameEn: 'Vault', icon: 'vault' },
      { name: 'Tỷ lệ', nameEn: 'Pie chart', icon: 'chart-pie' },
      { name: 'Công lý', nameEn: 'Justice', icon: 'scale-balanced' },
      { name: 'Chữ ký', nameEn: 'Signature', icon: 'signature' },
      { name: 'Con dấu', nameEn: 'Stamp', icon: 'stamp' },
      { name: 'Đầu tư', nameEn: 'Investment', icon: 'money-bill-trend-up' },
      { name: 'Địa điểm', nameEn: 'Landmark', icon: 'landmark' },
    ],
  },
  {
    title: 'Cá nhân & Giải trí',
    tabIcon: 'gamepad',
    icons: [
      { name: 'Cá nhân', nameEn: 'User', icon: 'user' },
      { name: 'Nhóm', nameEn: 'Users', icon: 'users' },
      { name: 'Thú cưng', nameEn: 'Pet', icon: 'paw' },
      { name: 'Quà tặng', nameEn: 'Gift', icon: 'gift' },
      { name: 'Quần áo', nameEn: 'Shirt', icon: 'shirt' },
      { name: 'Trò chơi', nameEn: 'Game', icon: 'gamepad' },
      { name: 'Vé', nameEn: 'Ticket', icon: 'ticket' },
      { name: 'Chụp ảnh', nameEn: 'Camera', icon: 'camera' },
      { name: 'Phim', nameEn: 'Film', icon: 'film' },
      { name: 'Âm nhạc', nameEn: 'Music', icon: 'music' },
      { name: 'Điện ảnh', nameEn: 'Clapperboard', icon: 'clapperboard' },
      { name: 'Cắt tóc', nameEn: 'Scissors', icon: 'scissors' },
      { name: 'Thư giãn', nameEn: 'Spa', icon: 'spa' },
      { name: 'Trẻ em', nameEn: 'Baby', icon: 'baby' },
      { name: 'Pháp thuật', nameEn: 'Magic', icon: 'hat-wizard' },
      { name: 'Xúc xắc', nameEn: 'Dice', icon: 'dice' },
      { name: 'Mặt nạ', nameEn: 'Mask', icon: 'mask' },
      { name: 'Ghép hình', nameEn: 'Puzzle', icon: 'puzzle-piece' },
      { name: 'Guitar', nameEn: 'Guitar', icon: 'guitar' },
      { name: 'Tai nghe', nameEn: 'Headphones', icon: 'headphones' },
      { name: 'Radio', nameEn: 'Radio', icon: 'radio' },
      { name: 'Bóng chày', nameEn: 'Baseball', icon: 'baseball' },
      { name: 'Bóng rổ', nameEn: 'Basketball', icon: 'basketball' },
      { name: 'Bóng đá', nameEn: 'Football', icon: 'football' },
    ],
  },
  {
    title: 'Gia đình & Sự kiện',
    tabIcon: 'cake-candles',
    icons: [
      { name: 'Sinh nhật', nameEn: 'Birthday', icon: 'cake-candles' },
      { name: 'Rượu chai', nameEn: 'Wine bottle', icon: 'wine-bottle' },
      { name: 'Karaoke', nameEn: 'Microphone', icon: 'microphone' },
      { name: 'Nhà thờ', nameEn: 'Church', icon: 'church' },
      { name: 'Nhà thờ Hồi giáo', nameEn: 'Mosque', icon: 'mosque' },
      { name: 'Chùa', nameEn: 'Vihara', icon: 'vihara' },
      { name: 'Lịch hẹn', nameEn: 'Calendar', icon: 'calendar-check' },
      { name: 'Thông báo', nameEn: 'Bell', icon: 'bell' },
      { name: 'Điện thoại', nameEn: 'Phone', icon: 'phone' },
      { name: 'Thư từ', nameEn: 'Envelope', icon: 'envelope' },
      { name: 'Halloween', nameEn: 'Ghost', icon: 'ghost' },
      { name: 'Đám cưới', nameEn: 'Wedding', icon: 'venus-mars' },
      { name: 'Xe nôi', nameEn: 'Stroller', icon: 'baby-carriage' },
      { name: 'Thai kỳ', nameEn: 'Pregnant', icon: 'person-pregnant' },
      { name: 'Hòa bình', nameEn: 'Dove', icon: 'dove' },
      { name: 'Từ thiện', nameEn: 'Charity', icon: 'hand-holding-heart' },
      { name: 'Vui vẻ', nameEn: 'Smile', icon: 'face-smile' },
      { name: 'May mắn', nameEn: 'Clover', icon: 'clover' },
    ],
  },
  {
    title: 'Khác',
    tabIcon: 'ellipsis',
    icons: [
      { name: 'Khác', nameEn: 'Other', icon: 'ellipsis' },
      { name: 'Hỏi đáp', nameEn: 'Question', icon: 'circle-question' },
      { name: 'Bảo mật', nameEn: 'Shield', icon: 'shield-halved' },
      { name: 'Lưu trữ', nameEn: 'Archive', icon: 'box-archive' },
      { name: 'Thời tiết', nameEn: 'Cloud', icon: 'cloud' },
      { name: 'Ban đêm', nameEn: 'Moon', icon: 'moon' },
      { name: 'Ban ngày', nameEn: 'Sun', icon: 'sun' },
      { name: 'Lá cây', nameEn: 'Leaf', icon: 'leaf' },
      { name: 'Cây cối', nameEn: 'Tree', icon: 'tree' },
      { name: 'Hà mã', nameEn: 'Hippo', icon: 'hippo' },
      { name: 'Rồng', nameEn: 'Dragon', icon: 'dragon' },
      { name: 'Robot', nameEn: 'Robot', icon: 'robot' },
      { name: 'Côn trùng', nameEn: 'Bug', icon: 'bug' },
    ],
  },
];
