export const ICON_CATEGORIES = [
  {
    title: 'Ăn uống & Mua sắm',
    tabIcon: 'cart-shopping',
    icons: [
      'utensils',
      'mug-hot',
      'pizza-slice',
      'burger',
      'ice-cream',
      'wine-glass',
      'beer-mug-empty',
      'cart-shopping',
      'bag-shopping',
      'basket-shopping',
      'store',
      'tag',
      'shrimp',
      'carrot',
      'apple-whole',
      'bowl-food',
      'cookie',
      'fish',
      'hotdog',
      'egg',
      'candy-cane',
      'lollipop',
    ],
  },
  {
    title: 'Di chuyển & Du lịch',
    tabIcon: 'car-side',
    icons: [
      'car-side',
      'motorcycle',
      'bus',
      'train',
      'plane',
      'gas-pump',
      'oil-can',
      'wrench',
      'taxi',
      'bicycle',
      'map-location-dot',
      'suitcase',
      'caravan',
      'ship',
      'truck',
      'helmet-safety',
      'traffic-light',
      'anchor',
      'passport',
      'hotel',
      'mountain-sun',
      'umbrella-beach',
    ],
  },
  {
    title: 'Nhà cửa & Tiện ích',
    tabIcon: 'house',
    icons: [
      'house',
      'house-user',
      'bolt',
      'faucet',
      'droplet',
      'couch',
      'tv',
      'bed',
      'shower',
      'kitchen-set',
      'broom',
      'plug',
      'wifi',
      'trash-can',
      'key',
      'fan',
      'hammer',
      'paint-roller',
      'screwdriver-wrench',
      'snowflake',
      'fire-burner',
      'toilet-paper',
      'chair',
    ],
  },
  {
    title: 'Sức khỏe & Giáo dục',
    tabIcon: 'graduation-cap',
    icons: [
      'heart-pulse',
      'stethoscope',
      'pills',
      'hospital',
      'tooth',
      'graduation-cap',
      'book',
      'school',
      'brain',
      'microscope',
      'dumbbell',
      'user-doctor',
      'bandage',
      'syringe',
      'kit-medical',
      'glasses',
      'dna',
      'books',
      'pen-nib',
      'pencil',
      'palette',
      'chalkboard',
    ],
  },
  {
    title: 'Tài chính & Công việc',
    tabIcon: 'money-bill-1',
    icons: [
      'money-bill-1',
      'money-check-dollar',
      'briefcase',
      'credit-card',
      'bank',
      'coins',
      'receipt',
      'chart-line',
      'piggy-bank',
      'wallet',
      'hand-holding-dollar',
      'sack-dollar',
      'file-invoice-dollar',
      'building-columns',
      'gem',
      'vault',
      'chart-pie',
      'scale-balanced',
      'signature',
      'stamp',
      'money-bill-trend-up',
      'landmark',
    ],
  },
  {
    title: 'Cá nhân & Giải trí',
    tabIcon: 'gamepad',
    icons: [
      'user',
      'users',
      'paw',
      'gift',
      'shirt',
      'gamepad',
      'ticket',
      'camera',
      'film',
      'music',
      'clapperboard',
      'scissors',
      'spa',
      'baby',
      'hat-wizard',
      'dice',
      'mask',
      'puzzle-piece',
      'guitar',
      'headphones',
      'radio',
      'baseball',
      'basketball',
      'football',
    ],
  },
  {
    title: 'Gia đình & Sự kiện',
    tabIcon: 'cake-candles',
    icons: [
      'cake-candles',
      'wine-bottle',
      'microphone',
      'church',
      'mosque',
      'vihara',
      'calendar-check',
      'bell',
      'phone',
      'envelope',
      'ghost',
      'rings-wedding',
      'baby-carriage',
      'person-pregnant',
      'dove',
      'hand-holding-heart',
      'face-smile',
      'fireworks',
      'balloon',
      'clover',
      'tshirt',
    ],
  },
  {
    title: 'Khác',
    tabIcon: 'ellipsis',
    icons: [
      'ellipsis',
      'circle-question',
      'shield-halved',
      'box-archive',
      'cloud',
      'moon',
      'sun',
      'leaf',
      'tree',
      'hippo',
      'dragon',
      'robot',
      'bug',
    ],
  },
];
