import { COLORS } from '@/theme';

export enum INSTALLMENT_STATUS {
  ACTIVE = 'ACTIVE',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export const INSTALLMENT_STATUS_COLOR = {
  [INSTALLMENT_STATUS.ACTIVE]: COLORS.green,
  [INSTALLMENT_STATUS.COMPLETED]: COLORS.gray,
  [INSTALLMENT_STATUS.CANCELLED]: COLORS.red,
};

export const INSTALLMENT_ITEM_STATUS = {
  PENDING: 'PENDING',
  BILLED: 'BILLED',
};
